[package]
name = "bridge-aptos"
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
#AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
memo = "_"